export enum KeywordType {
  Frontend = 'Frontend',
  Backend = 'Backend',
  Database = 'Database',
  DevOps = 'DevOps',
  Misc = 'Misc',
}
export const keywords = {
  [KeywordType.Frontend]: [
    'React',
    'Redux',
    'Angular',
    'Vue',
    'Vue 2',
    'Vue 3',
    'HTML',
    'CSS',
    'SASS',
    'LESS',
    'Bootstrap',
    'Material UI',
    'jQuery',
    'JavaScript',
    'TypeScript',
  ],
  [KeywordType.Backend]: [
    'TypeScript',
    'Node',
    'Express',
    'Python',
    'Flask',
    'Django',
    'Java',
    'Spring',
    'C#',
    'ASP.NET',
    'PHP',
    'Laravel',
    'Ruby',
    'Ruby on Rails',
    'Go',
    'Rust',
    'GraphQL',
    'GraphQL (Apollo)',
    'REST',
    'Node (Express)',
  ],
  [KeywordType.Database]: [
    'MySQL',
    'PostgreSQL',
    'MongoDB',
    'Redis',
    'SQL',
    'NoSQL',
    'Oracle',
    'DB2',
    'SQLite',
    'MariaDB',
  ],
  [KeywordType.DevOps]: [
    'Docker',
    'Kubernetes',
    'AWS',
    'Azure',
    'GCP',
    'Jenkins',
    'GitLab CI',
    'Travis CI',
    'Circle CI',
    'Ansible',
    'Terraform',
    'Puppet',
  ],
  [KeywordType.Misc]: [],
};
